export const PARALLAX_BANNER_ANIMATION_SPEED = 10;

export const PARALLAX_BANNER_OUTER_BOUNDS_X = 10;
export const PARALLAX_BANNER_OUTER_BOUNDS_Y = 10;

export const PARALLAX_BANNER_IDLE_AMPLITUDE_X = 50;
export const PARALLAX_BANNER_IDLE_AMPLITUDE_Y = 30;
export const PARALLAX_BANNER_IDLE_FREQUENCY_X = 0.37;
export const PARALLAX_BANNER_IDLE_FREQUENCY_Y = 0.77;
